# Generated by Django 2.1 on 2018-09-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_slug',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
