# Generated by Django 2.1.3 on 2019-01-04 18:04

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_auto_20190104_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='quote',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
