# Generated by Django 2.1.7 on 2019-07-31 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_auto_20190412_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-date_created']},
        ),
    ]
