# Generated by Django 2.1.3 on 2019-01-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_auto_20190104_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='bq_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
