# Generated by Django 2.1 on 2018-09-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_auto_20180927_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
