# Generated by Django 2.1 on 2018-09-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0006_auto_20180927_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='user_name',
        ),
    ]
